# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
    tags:
        - v*
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-2019]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Get the version
      id: echo_get_version
      run: echo ::set-output name=VERSION::${{ github.ref }}
    
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo ${{ github.ref#refs/*/ }} | cut -d / -f 3)
      #uses: battila7/get-version-action@v2
      #run: echo ${{ steps.get_version.outputs.version }}
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    #- name: Setup NuGet
      #uses: NuGet/setup-nuget@v1.0.5
    
    #- name: Restore NuGet packages
      #run: nuget restore src\Eraki.UTTools.UTQuickLauncher.sln
    
    - name: Build the Solution
      run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\src\Eraki.UTTools.UTQuickLauncher.sln /p:Configuration="Release" /p:Version="${{steps.get_version.outputs.VERSION}}"
           
    - name: Upload Release Artifact
      #uses: actions/upload-artifact@v2
      #with:
        #name: UTQuickLauncher v${{steps.get_version.outputs.VERSION}}
        #path: src\Eraki.UTTools.UTQuickLauncher.WinForm\bin\Release\UnrealTournamentLauncher.exe
      uses: svenstaro/upload-release-action@v2
      with:
        #asset_name: UTQuickLauncher v${{steps.get_version.outputs.VERSION}}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: src\Eraki.UTTools.UTQuickLauncher.WinForm\bin\Release\UnrealTournamentLauncher.exe
        tag: ${{ github.ref }}
        file_glob: true
        prerelease: true
